[package]
name = "simple-auth-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-auth-model = { path = "../simple-auth-model" }
simple-auth-service = { path = "../simple-auth-service" }