[package]
name = "simple-auth-web"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-auth-model = { path = "../simple-auth-model" }
simple-auth-crud = { path = "../simple-auth-crud" }
actix-web = "4.3.1"
actix-rt = "2.8.0"